name: mandhiram
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  otp_text_field: ^1.1.3
  flutter_screenutil: ^5.6.0
  smooth_page_indicator: ^1.0.0+2
  gallery_view: ^1.0.0+1
  flutter_reaction_button: ^2.0.1+2
  any_link_preview: ^2.0.9
  url_launcher: ^6.1.7
  share_plus: ^6.3.0
  dio: ^4.0.6
  get_storage: ^2.0.3

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/
    - assets/image/
    - assets/fonts/


  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 800
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 300
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 400
        - asset: assets/fonts/Quicksand-Regular.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 700

